// <auto-generated />
using System;
using EFCoreRepositoryDatalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreRepositoryDatalog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181010231243_initial-003")]
    partial class initial003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Address", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Code")
                        .HasMaxLength(12);

                    b.Property<string>("Line001")
                        .HasMaxLength(50);

                    b.Property<string>("Line002")
                        .HasMaxLength(50);

                    b.Property<string>("Line003")
                        .HasMaxLength(50);

                    b.Property<string>("Line004")
                        .HasMaxLength(50);

                    b.Property<string>("Line005")
                        .HasMaxLength(50);

                    b.Property<Guid?>("T_PersonID");

                    b.HasKey("ID");

                    b.HasIndex("T_PersonID");

                    b.ToTable("T_Address");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_DbLog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Detail");

                    b.Property<string>("Device");

                    b.Property<string>("Event")
                        .HasMaxLength(25);

                    b.Property<DateTime>("LogDateTime");

                    b.Property<string>("TableName")
                        .HasMaxLength(50);

                    b.Property<string>("TablePKName");

                    b.Property<string>("TablePKValue");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.HasIndex("LogDateTime");

                    b.ToTable("T_DBLog");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Lookup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Lookup");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("T_Lookup");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("T_Person");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Address", b =>
                {
                    b.HasOne("EFCoreRepositoryDatalog.T_Person")
                        .WithMany("Addresses")
                        .HasForeignKey("T_PersonID");
                });
#pragma warning restore 612, 618
        }
    }
}
