// <auto-generated />
using System;
using EFCoreRepositoryDatalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreRepositoryDatalog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181010190030_initial-001")]
    partial class initial001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Address", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Code")
                        .HasMaxLength(12);

                    b.Property<string>("Line001")
                        .HasMaxLength(50);

                    b.Property<string>("Line002")
                        .HasMaxLength(50);

                    b.Property<string>("Line003")
                        .HasMaxLength(50);

                    b.Property<string>("Line004")
                        .HasMaxLength(50);

                    b.Property<string>("Line005")
                        .HasMaxLength(50);

                    b.Property<Guid?>("T_PersonID");

                    b.HasKey("ID");

                    b.HasIndex("T_PersonID");

                    b.ToTable("T_Address");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_DbLog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Device");

                    b.Property<string>("Event");

                    b.Property<DateTime>("LogDateTime");

                    b.Property<string>("NewValue");

                    b.Property<string>("OriginalValue");

                    b.Property<string>("TableName");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("T_DBLog");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Lookup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("Lookup");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("T_Lookup");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("T_Person");
                });

            modelBuilder.Entity("EFCoreRepositoryDatalog.T_Address", b =>
                {
                    b.HasOne("EFCoreRepositoryDatalog.T_Person")
                        .WithMany("Addresses")
                        .HasForeignKey("T_PersonID");
                });
#pragma warning restore 612, 618
        }
    }
}
